// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChittyChatServiceClient is the client API for ChittyChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TimeAskServiceClient interface {
	GetTime(ctx context.Context, opts ...grpc.CallOption) (TimeAskService_GetTimeClient, error)
}

type chittyChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChittyChatServiceClient(cc grpc.ClientConnInterface) ChittyChatServiceClient {
	return &chittyChatServiceClient{cc}
}

func (c *timeAskServiceClient) GetTime(ctx context.Context, opts ...grpc.CallOption) (TimeAskService_GetTimeClient, error) {
	stream, err := c.cc.NewStream(ctx, &TimeAskService_ServiceDesc.Streams[0], "/chittychat_skrrrt.TimeAskService/GetTime", opts...)
	if err != nil {
		return nil, err
	}
	x := &timeAskServiceGetTimeClient{stream}
	return x, nil
}

type TimeAskService_GetTimeClient interface {
	Send(*Message) error
	Recv() (*MessageAck, error)
	grpc.ClientStream
}

type timeAskServiceGetTimeClient struct {
	grpc.ClientStream
}

func (x *timeAskServiceGetTimeClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *timeAskServiceGetTimeClient) Recv() (*MessageAck, error) {
	m := new(MessageAck)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatServiceServer is the server API for ChittyChatService service.
// All implementations must embed UnimplementedChittyChatServiceServer
// for forward compatibility
type TimeAskServiceServer interface {
	GetTime(TimeAskService_GetTimeServer) error
	mustEmbedUnimplementedTimeAskServiceServer()
}

// UnimplementedChittyChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChittyChatServiceServer struct {
}

func (UnimplementedTimeAskServiceServer) GetTime(TimeAskService_GetTimeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTime not implemented")
}
func (UnimplementedChittyChatServiceServer) mustEmbedUnimplementedChittyChatServiceServer() {}

// UnsafeChittyChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChittyChatServiceServer will
// result in compilation errors.
type UnsafeChittyChatServiceServer interface {
	mustEmbedUnimplementedChittyChatServiceServer()
}

func RegisterChittyChatServiceServer(s grpc.ServiceRegistrar, srv ChittyChatServiceServer) {
	s.RegisterService(&ChittyChatService_ServiceDesc, srv)
}

func _TimeAskService_GetTime_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TimeAskServiceServer).GetTime(&timeAskServiceGetTimeServer{stream})
}

type TimeAskService_GetTimeServer interface {
	Send(*MessageAck) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type timeAskServiceGetTimeServer struct {
	grpc.ServerStream
}

func (x *timeAskServiceGetTimeServer) Send(m *MessageAck) error {
	return x.ServerStream.SendMsg(m)
}

func (x *timeAskServiceGetTimeServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatService_ServiceDesc is the grpc.ServiceDesc for ChittyChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TimeAskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chittychat_skrrrt.TimeAskService",
	HandlerType: (*TimeAskServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTime",
			Handler:       _TimeAskService_GetTime_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/proto.proto",
}
